plugins {
    id 'com.gtnewhorizons.gtnhconvention'
}

version = providers.gradleProperty('modVersion').get()
group = providers.gradleProperty('modGroup').get()

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

sourceSets {
    main {
        java {
            srcDir project.projectDir
            include 'assets/recipehandler/**/*.java'
        }
        resources {
            srcDir project.projectDir
            include 'assets/recipehandler/lang/**/*.lang'
            include 'mcmod.info'
            include 'pack.mcmeta'
        }
    }
}

tasks.named('jar') {
    includeEmptyDirs = false
}
