buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "anatawa12"
            url = "https://maven.anatawa12.com/repository/maven-public/"
        }
    }
    dependencies {
        classpath('com.anatawa12.forge:ForgeGradle:1.2-1.0.+') {
            changing = true
        }
    }
}

apply plugin: 'forge'

archivesBaseName = "NoMoreRecipeConflict"
version = "0.3"

sourceCompatibility = 1.8
targetCompatibility = 1.8

minecraft {
    version = "1.7.10-10.13.2.1230"
    runDir = "eclipse"
    replace '$version', project.version
}

sourceSets {
    main {
        java {
            srcDir project.projectDir
            include 'assets/recipehandler/**/*.java'
        }
        resources {
            srcDir project.projectDir
            include 'assets/recipehandler/lang/**/*.lang'
            include 'mcmod.info'
            include 'pack.mcmeta'
        }
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    filesMatching('mcmod.info') {
        expand(version: project.version, mcversion: project.minecraft.version)
    }
}

jar {
    includeEmptyDirs = false
    exclude '**/*.java'
    classifier = "(${minecraft.version})"
    archiveName = "${archivesBaseName}-${version}${classifier}.${extension}"
}
